name: proyecto_papeleria
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.0
  google_fonts: ^2.3.2
  animate_do: ^2.1.0
  cached_network_image: ^3.2.0
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.1.14
  image_picker: ^0.8.5
  form_field_validator: ^1.1.0
  get: ^4.6.1
  firebase_auth: ^3.3.4
  flutter_staggered_grid_view: ^0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/